/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        student: {
          primary: '#2b6c00',
          'primary-container': '#8ce35d',
          'on-primary-container': '#276400',
          'primary-fixed': '#a0f970',
          'on-primary': '#ffffff',
          secondary: '#6b5e23',
          'secondary-container': '#f2df97',
          'on-secondary-container': '#6f6227',
          tertiary: '#506449',
          'tertiary-container': '#bed4b3',
          'on-tertiary-container': '#495c42',
          'tertiary-fixed': '#d3e9c7',
          surface: '#fafaf4',
          'surface-bright': '#fafaf4',
          'surface-container': '#eeeee9',
          'surface-container-low': '#f4f4ee',
          'surface-container-high': '#e8e8e3',
          'surface-container-highest': '#e3e3de',
          'surface-container-lowest': '#ffffff',
          'surface-variant': '#e3e3de',
          'on-surface': '#1a1c19',
          'on-surface-variant': '#404a39',
          'on-background': '#1a1c19',
          background: '#f8f9fa',
          outline: '#707a68',
          'outline-variant': '#c0cab4',
          error: '#ba1a1a',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'on-error': '#ffffff',
          'on-primary-fixed': '#082100',
          'primary-fixed-dim': '#85dc57',
          'secondary-fixed': '#f5e29a',
          'inverse-surface': '#2f312e',
          'inverse-on-surface': '#f1f1ec',
        },
        "surface-tint": "#2b6c00",
        "outline-variant": "#c0cab4",
        "surface-container-low": "#f4f4ee",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e3",
        "on-error-container": "#93000a",
        "secondary": "#2b6c00",
        "surface": "#fafaf4",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1ec",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#85dc57",
        "on-primary-container": "#276400",
        "secondary-container": "#276400",
        "primary-fixed": "#a0f970",
        "tertiary": "#506449",
        "outline": "#707a68",
        "primary-fixed-dim": "#85dc57",
        "secondary-fixed": "#f5e29a",
        "on-secondary": "#ffffff",
        "primary-container": "#8ce35d",
        "primary": "#2b6c00",
        "surface-container-highest": "#e3e3de",
        "error": "#ba1a1a",
        "on-surface": "#1a1c19",
        "on-tertiary-container": "#495c42",
        "on-primary-fixed-variant": "#1e5100",
        "surface-container": "#eeeee9",
        "on-tertiary-fixed-variant": "#394c33",
        "surface-dim": "#dadad5",
        "on-secondary-fixed-variant": "#1e5100",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d3e9c7",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#082100",
        "surface-variant": "#e3e3de",
        "on-tertiary-fixed": "#0f1f0b",
        "on-background": "#1a1c19",
        "on-primary-fixed": "#082100",
        "on-surface-variant": "#404a39",
        "tertiary-container": "#bed4b3",
        "on-secondary-container": "#ffffff",
        "surface-bright": "#fafaf4",
        "background": "#fafaf4",
        "inverse-primary": "#85dc57",
        "inverse-surface": "#2f312e",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
        brand: "24px",
      },
      spacing: {
        base: "8px",
        "section-padding-mobile": "64px",
        gutter: "24px",
        "section-padding-desktop": "120px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "display-hero-mobile": ["Geist", "sans-serif"],
        "headline-section-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-section": ["Geist", "sans-serif"],
        "display-hero": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "student": ["Hanken Grotesk", "Geist", "sans-serif"],
      },
      fontSize: {
        "student-display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "student-headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "student-headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "student-body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "student-body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "student-label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-hero-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-section-mobile": ["30px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-section": ["42px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
