/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fa",
        "inverse-primary": "#c6c6c7",
        "inverse-surface": "#2e3132",
        "background": "#f8f9fa",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-tint": "#5d5f5f",
        "outline-variant": "#c4c7c8",
        "surface-container-low": "#f3f4f5",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-error-container": "#93000a",
        "secondary": "#0051d5",
        "surface": "#f8f9fa",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#747676",
        "secondary-container": "#316bf3",
        "primary-fixed": "#e2e2e2",
        "tertiary": "#565e74",
        "outline": "#747878",
        "primary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#dbe1ff",
        "on-secondary": "#ffffff",
        "primary-container": "#ffffff",
        "primary": "#5d5f5f",
        "surface-container-highest": "#e1e3e4",
        "error": "#ba1a1a",
        "on-surface": "#191c1d",
        "on-tertiary-container": "#6e758d",
        "on-primary-fixed-variant": "#454747",
        "surface-container": "#edeeef",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#003ea8",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#dae2fd",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#00174b",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#131b2e",
        "on-background": "#191c1d",
        "on-primary-fixed": "#1a1c1c",
        "on-surface-variant": "#444748",
        "tertiary-container": "#ffffff",
        "on-secondary-container": "#fefcff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "section-padding-mobile": "64px",
        gutter: "24px",
        "section-padding-desktop": "120px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "display-hero-mobile": ["Geist", "sans-serif"],
        "headline-section-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-section": ["Geist", "sans-serif"],
        "display-hero": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-hero-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-section-mobile": ["30px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-section": ["42px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
